
name: build

on:
  workflow_dispatch:
    branches: master
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports: 
          - 6379:6379

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run program
      run: 
        python source/main.py BUILD
